### ISSUE TITLE
Problem with vertex weights while converting to collada (.dae)

### ISSUE THREAD

**Issue by Pavel3333** [atacms/wot-model-converter#1]
![image](https://user-images.githubusercontent.com/8133310/61795482-2db2d700-ae2c-11e9-8cd2-e9fe0f99eb78.png)
[hd_env_UNI_623_RotaryExcavator_Chassis.zip](https://github.com/atacms/wot-model-converter/files/3426884/hd_env_UNI_623_RotaryExcavator_Chassis.zip)

**Comment by atacms** [comment]
this will have to wait a while. need to fix the UML mod first.

**Comment by atacms** [comment]
This static model was wrongly identified as skinned because there are a few white space around the 'Scene Root' of\<node\> in \<renderSet\>. Fixed now. 

This come very late so it probably couldn't help you.
